%% Constants
global BEHAVIORAL_SAMPLE_RATE NEURONAL_SAMPLE_RATE BEHAVIORAL_SAMPLES_PER_TEMPORAL_BIN NUMBER_OF_ANGLE_BINS CENTER_OF_ANGLE_BINS TEMPORAL_TIME_BIN;

BEHAVIORAL_SAMPLE_RATE = 39.0625; % Hz
NEURONAL_SAMPLE_RATE = 20000; %Hz
BEHAVIORAL_SAMPLES_PER_TEMPORAL_BIN = 4; %for now, we use only integer number of samples
NUMBER_OF_ANGLE_BINS = 40;
CENTER_OF_ANGLE_BINS = [0.5 * (2 * pi) / NUMBER_OF_ANGLE_BINS:...
                        (2 * pi) / NUMBER_OF_ANGLE_BINS:...
                        2 * pi - 0.5 * (2 * pi) / NUMBER_OF_ANGLE_BINS];
TEMPORAL_TIME_BIN = BEHAVIORAL_SAMPLES_PER_TEMPORAL_BIN / BEHAVIORAL_SAMPLE_RATE;

% Head directionality criterion (find_head_direction_neurons.m)
global FIRING_RATE_THRESHOLD RAYLEIGH_VECTOR_LENGTH_THRESHOLD;
FIRING_RATE_THRESHOLD = 5; % Hz
RAYLEIGH_VECTOR_LENGTH_THRESHOLD = 0.5;